// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.driveTest.subsystems;

import org.usfirst.frc253.driveTest.Robot;
import org.usfirst.frc253.driveTest.RobotMap;
import org.usfirst.frc253.driveTest.commands.*;
import org.usfirst.frc253.driveTest.profiles.Constants;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.StatusFrameEnhanced;
import com.ctre.phoenix.motorcontrol.can.*;

import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
	private double kP = 0.540;
	private double kI = 0.00052;
	private double kD = 5;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final TalonSRX leftFront = RobotMap.driveTrainLeftFront;
    private final TalonSRX leftBack = RobotMap.driveTrainLeftBack;
    private final TalonSRX rightFront = RobotMap.driveTrainRightFront;
    private final TalonSRX rightBack = RobotMap.driveTrainRightBack;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public DriveTrain(){
    	
    	leftFront.follow(leftBack);
    	rightFront.follow(rightBack);
    	
    	leftFront.setInverted(false);
    	rightFront.setInverted(true);
    	leftBack.setInverted(true);
    	rightBack.setInverted(true);
    	
    	leftBack.setStatusFramePeriod(StatusFrameEnhanced.Status_10_MotionMagic, 50, Constants.kTimeoutMs); 
		leftBack.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, 10);
		
		rightBack.setStatusFramePeriod(StatusFrameEnhanced.Status_10_MotionMagic, 50, Constants.kTimeoutMs); 
		rightBack.configSelectedFeedbackSensor(FeedbackDevice.CTRE_MagEncoder_Relative, 0, 10);
		
		leftBack.setSensorPhase(false);
		rightBack.setSensorPhase(true);

    	leftBack.configNeutralDeadband(Constants.kNeutralDeadband, Constants.kTimeoutMs);
    	rightBack.configNeutralDeadband(Constants.kNeutralDeadband, Constants.kTimeoutMs);
//35074964382
		leftBack.config_kF(0, 0.35074964382, Constants.kTimeoutMs);
		leftBack.config_kP(0, kP, Constants.kTimeoutMs);
		leftBack.config_kI(0, kI, Constants.kTimeoutMs);
		leftBack.config_kD(0, kD, Constants.kTimeoutMs);

		rightBack.config_kF(0, 0.36910309422, Constants.kTimeoutMs);
		rightBack.config_kP(0, kP, Constants.kTimeoutMs);
		rightBack.config_kI(0, kI, Constants.kTimeoutMs);
		rightBack.config_kD(0, kD, Constants.kTimeoutMs);

		/* Our profile uses 10ms timing */
		leftBack.configMotionProfileTrajectoryPeriod(50, Constants.kTimeoutMs); 
		rightBack.configMotionProfileTrajectoryPeriod(50, Constants.kTimeoutMs); 
		/*
		 * status 10 provides the trajectory target for motion profile AND
		 * motion magic
		 */
    }
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new TankDrive());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public TalonSRX getTalonRight(){
    	return rightBack;
    }
    
    public TalonSRX getTalonLeft(){
    	return leftBack;
    }
    
    public void drive(double left, double right){
    	leftBack.set(ControlMode.PercentOutput, -left);
    	rightBack.set(ControlMode.PercentOutput, -right);
    }
}

