// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.driveTest.subsystems;

import org.usfirst.frc253.driveTest.RobotMap;
import org.usfirst.frc253.driveTest.commands.*;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.StatusFrameEnhanced;
import com.ctre.phoenix.motorcontrol.can.*;

import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

import edu.wpi.first.wpilibj.command.Subsystem;


public class Intake extends Subsystem {


	private final Spark sparkLeft = RobotMap.sparkLeft;
	private final Spark sparkRight = RobotMap.sparkRight;
    public Intake(){
    
    	
    	}

    public void initDefaultCommand() {
    	


    }
    public void suckIn(){
    	sparkLeft.set(.5);
    	sparkRight.set(-.5);
    }
    
    public void ejectOut(){
    	sparkLeft.set(-.5);
    	sparkRight.set(.5);
    }
    public void stopit(){
    	sparkLeft.set(0);
    	sparkRight.set(0);
    	
    }
}